name: Crystal CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install
      - name: Lint with ameba
        run: ./bin/ameba
      - name: Check formatting
        run: crystal tool format --check
      - name: Run specs
        run: crystal spec
